// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/models.proto

package cl.svasquezm.proto;

public final class Models {
  private Models() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cl.svasquezm.proto.Pet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code cl.svasquezm.proto.Pet}
   */
  public  static final class Pet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cl.svasquezm.proto.Pet)
      PetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pet.newBuilder() to construct.
    private Pet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pet() {
      type_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Pet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_Pet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_Pet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cl.svasquezm.proto.Models.Pet.class, cl.svasquezm.proto.Models.Pet.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cl.svasquezm.proto.Models.Pet)) {
        return super.equals(obj);
      }
      cl.svasquezm.proto.Models.Pet other = (cl.svasquezm.proto.Models.Pet) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cl.svasquezm.proto.Models.Pet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cl.svasquezm.proto.Models.Pet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.Pet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cl.svasquezm.proto.Models.Pet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.Pet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cl.svasquezm.proto.Models.Pet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.Pet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cl.svasquezm.proto.Models.Pet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.Pet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cl.svasquezm.proto.Models.Pet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.Pet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cl.svasquezm.proto.Models.Pet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cl.svasquezm.proto.Models.Pet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cl.svasquezm.proto.Pet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cl.svasquezm.proto.Pet)
        cl.svasquezm.proto.Models.PetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_Pet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_Pet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cl.svasquezm.proto.Models.Pet.class, cl.svasquezm.proto.Models.Pet.Builder.class);
      }

      // Construct using cl.svasquezm.proto.Models.Pet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_Pet_descriptor;
      }

      @java.lang.Override
      public cl.svasquezm.proto.Models.Pet getDefaultInstanceForType() {
        return cl.svasquezm.proto.Models.Pet.getDefaultInstance();
      }

      @java.lang.Override
      public cl.svasquezm.proto.Models.Pet build() {
        cl.svasquezm.proto.Models.Pet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cl.svasquezm.proto.Models.Pet buildPartial() {
        cl.svasquezm.proto.Models.Pet result = new cl.svasquezm.proto.Models.Pet(this);
        result.type_ = type_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cl.svasquezm.proto.Models.Pet) {
          return mergeFrom((cl.svasquezm.proto.Models.Pet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cl.svasquezm.proto.Models.Pet other) {
        if (other == cl.svasquezm.proto.Models.Pet.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cl.svasquezm.proto.Models.Pet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cl.svasquezm.proto.Models.Pet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cl.svasquezm.proto.Pet)
    }

    // @@protoc_insertion_point(class_scope:cl.svasquezm.proto.Pet)
    private static final cl.svasquezm.proto.Models.Pet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cl.svasquezm.proto.Models.Pet();
    }

    public static cl.svasquezm.proto.Models.Pet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pet>
        PARSER = new com.google.protobuf.AbstractParser<Pet>() {
      @java.lang.Override
      public Pet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cl.svasquezm.proto.Models.Pet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cl.svasquezm.proto.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 2;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 2;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.cl.svasquezm.proto.User.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.cl.svasquezm.proto.User.Type type = 3;</code>
     * @return The type.
     */
    cl.svasquezm.proto.Models.User.Type getType();

    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    java.util.List<cl.svasquezm.proto.Models.Pet> 
        getPetsList();
    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    cl.svasquezm.proto.Models.Pet getPets(int index);
    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    int getPetsCount();
    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    java.util.List<? extends cl.svasquezm.proto.Models.PetOrBuilder> 
        getPetsOrBuilderList();
    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    cl.svasquezm.proto.Models.PetOrBuilder getPetsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cl.svasquezm.proto.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cl.svasquezm.proto.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      email_ = "";
      type_ = 0;
      pets_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                pets_ = new java.util.ArrayList<cl.svasquezm.proto.Models.Pet>();
                mutable_bitField0_ |= 0x00000001;
              }
              pets_.add(
                  input.readMessage(cl.svasquezm.proto.Models.Pet.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          pets_ = java.util.Collections.unmodifiableList(pets_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cl.svasquezm.proto.Models.User.class, cl.svasquezm.proto.Models.User.Builder.class);
    }

    /**
     * Protobuf enum {@code cl.svasquezm.proto.User.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WEB = 0;</code>
       */
      WEB(0),
      /**
       * <code>MOBILE = 1;</code>
       */
      MOBILE(1),
      /**
       * <code>ADMIN = 2;</code>
       */
      ADMIN(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>WEB = 0;</code>
       */
      public static final int WEB_VALUE = 0;
      /**
       * <code>MOBILE = 1;</code>
       */
      public static final int MOBILE_VALUE = 1;
      /**
       * <code>ADMIN = 2;</code>
       */
      public static final int ADMIN_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return WEB;
          case 1: return MOBILE;
          case 2: return ADMIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cl.svasquezm.proto.Models.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cl.svasquezm.proto.User.Type)
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 2;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 2;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 2;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.cl.svasquezm.proto.User.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.cl.svasquezm.proto.User.Type type = 3;</code>
     * @return The type.
     */
    public cl.svasquezm.proto.Models.User.Type getType() {
      @SuppressWarnings("deprecation")
      cl.svasquezm.proto.Models.User.Type result = cl.svasquezm.proto.Models.User.Type.valueOf(type_);
      return result == null ? cl.svasquezm.proto.Models.User.Type.UNRECOGNIZED : result;
    }

    public static final int PETS_FIELD_NUMBER = 4;
    private java.util.List<cl.svasquezm.proto.Models.Pet> pets_;
    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    public java.util.List<cl.svasquezm.proto.Models.Pet> getPetsList() {
      return pets_;
    }
    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    public java.util.List<? extends cl.svasquezm.proto.Models.PetOrBuilder> 
        getPetsOrBuilderList() {
      return pets_;
    }
    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    public int getPetsCount() {
      return pets_.size();
    }
    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    public cl.svasquezm.proto.Models.Pet getPets(int index) {
      return pets_.get(index);
    }
    /**
     * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
     */
    public cl.svasquezm.proto.Models.PetOrBuilder getPetsOrBuilder(
        int index) {
      return pets_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
      }
      if (type_ != cl.svasquezm.proto.Models.User.Type.WEB.getNumber()) {
        output.writeEnum(3, type_);
      }
      for (int i = 0; i < pets_.size(); i++) {
        output.writeMessage(4, pets_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
      }
      if (type_ != cl.svasquezm.proto.Models.User.Type.WEB.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      for (int i = 0; i < pets_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, pets_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cl.svasquezm.proto.Models.User)) {
        return super.equals(obj);
      }
      cl.svasquezm.proto.Models.User other = (cl.svasquezm.proto.Models.User) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (type_ != other.type_) return false;
      if (!getPetsList()
          .equals(other.getPetsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getPetsCount() > 0) {
        hash = (37 * hash) + PETS_FIELD_NUMBER;
        hash = (53 * hash) + getPetsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cl.svasquezm.proto.Models.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cl.svasquezm.proto.Models.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cl.svasquezm.proto.Models.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cl.svasquezm.proto.Models.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cl.svasquezm.proto.Models.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cl.svasquezm.proto.Models.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cl.svasquezm.proto.Models.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cl.svasquezm.proto.Models.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cl.svasquezm.proto.Models.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cl.svasquezm.proto.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cl.svasquezm.proto.User)
        cl.svasquezm.proto.Models.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cl.svasquezm.proto.Models.User.class, cl.svasquezm.proto.Models.User.Builder.class);
      }

      // Construct using cl.svasquezm.proto.Models.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPetsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        email_ = "";

        type_ = 0;

        if (petsBuilder_ == null) {
          pets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          petsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cl.svasquezm.proto.Models.internal_static_cl_svasquezm_proto_User_descriptor;
      }

      @java.lang.Override
      public cl.svasquezm.proto.Models.User getDefaultInstanceForType() {
        return cl.svasquezm.proto.Models.User.getDefaultInstance();
      }

      @java.lang.Override
      public cl.svasquezm.proto.Models.User build() {
        cl.svasquezm.proto.Models.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cl.svasquezm.proto.Models.User buildPartial() {
        cl.svasquezm.proto.Models.User result = new cl.svasquezm.proto.Models.User(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.email_ = email_;
        result.type_ = type_;
        if (petsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            pets_ = java.util.Collections.unmodifiableList(pets_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pets_ = pets_;
        } else {
          result.pets_ = petsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cl.svasquezm.proto.Models.User) {
          return mergeFrom((cl.svasquezm.proto.Models.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cl.svasquezm.proto.Models.User other) {
        if (other == cl.svasquezm.proto.Models.User.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (petsBuilder_ == null) {
          if (!other.pets_.isEmpty()) {
            if (pets_.isEmpty()) {
              pets_ = other.pets_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePetsIsMutable();
              pets_.addAll(other.pets_);
            }
            onChanged();
          }
        } else {
          if (!other.pets_.isEmpty()) {
            if (petsBuilder_.isEmpty()) {
              petsBuilder_.dispose();
              petsBuilder_ = null;
              pets_ = other.pets_;
              bitField0_ = (bitField0_ & ~0x00000001);
              petsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPetsFieldBuilder() : null;
            } else {
              petsBuilder_.addAllMessages(other.pets_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cl.svasquezm.proto.Models.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cl.svasquezm.proto.Models.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 2;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 2;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 2;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 2;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.cl.svasquezm.proto.User.Type type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.cl.svasquezm.proto.User.Type type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cl.svasquezm.proto.User.Type type = 3;</code>
       * @return The type.
       */
      public cl.svasquezm.proto.Models.User.Type getType() {
        @SuppressWarnings("deprecation")
        cl.svasquezm.proto.Models.User.Type result = cl.svasquezm.proto.Models.User.Type.valueOf(type_);
        return result == null ? cl.svasquezm.proto.Models.User.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.cl.svasquezm.proto.User.Type type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(cl.svasquezm.proto.Models.User.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cl.svasquezm.proto.User.Type type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<cl.svasquezm.proto.Models.Pet> pets_ =
        java.util.Collections.emptyList();
      private void ensurePetsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          pets_ = new java.util.ArrayList<cl.svasquezm.proto.Models.Pet>(pets_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cl.svasquezm.proto.Models.Pet, cl.svasquezm.proto.Models.Pet.Builder, cl.svasquezm.proto.Models.PetOrBuilder> petsBuilder_;

      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public java.util.List<cl.svasquezm.proto.Models.Pet> getPetsList() {
        if (petsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pets_);
        } else {
          return petsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public int getPetsCount() {
        if (petsBuilder_ == null) {
          return pets_.size();
        } else {
          return petsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public cl.svasquezm.proto.Models.Pet getPets(int index) {
        if (petsBuilder_ == null) {
          return pets_.get(index);
        } else {
          return petsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public Builder setPets(
          int index, cl.svasquezm.proto.Models.Pet value) {
        if (petsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePetsIsMutable();
          pets_.set(index, value);
          onChanged();
        } else {
          petsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public Builder setPets(
          int index, cl.svasquezm.proto.Models.Pet.Builder builderForValue) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          pets_.set(index, builderForValue.build());
          onChanged();
        } else {
          petsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public Builder addPets(cl.svasquezm.proto.Models.Pet value) {
        if (petsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePetsIsMutable();
          pets_.add(value);
          onChanged();
        } else {
          petsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public Builder addPets(
          int index, cl.svasquezm.proto.Models.Pet value) {
        if (petsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePetsIsMutable();
          pets_.add(index, value);
          onChanged();
        } else {
          petsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public Builder addPets(
          cl.svasquezm.proto.Models.Pet.Builder builderForValue) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          pets_.add(builderForValue.build());
          onChanged();
        } else {
          petsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public Builder addPets(
          int index, cl.svasquezm.proto.Models.Pet.Builder builderForValue) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          pets_.add(index, builderForValue.build());
          onChanged();
        } else {
          petsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public Builder addAllPets(
          java.lang.Iterable<? extends cl.svasquezm.proto.Models.Pet> values) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pets_);
          onChanged();
        } else {
          petsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public Builder clearPets() {
        if (petsBuilder_ == null) {
          pets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          petsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public Builder removePets(int index) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          pets_.remove(index);
          onChanged();
        } else {
          petsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public cl.svasquezm.proto.Models.Pet.Builder getPetsBuilder(
          int index) {
        return getPetsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public cl.svasquezm.proto.Models.PetOrBuilder getPetsOrBuilder(
          int index) {
        if (petsBuilder_ == null) {
          return pets_.get(index);  } else {
          return petsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public java.util.List<? extends cl.svasquezm.proto.Models.PetOrBuilder> 
           getPetsOrBuilderList() {
        if (petsBuilder_ != null) {
          return petsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pets_);
        }
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public cl.svasquezm.proto.Models.Pet.Builder addPetsBuilder() {
        return getPetsFieldBuilder().addBuilder(
            cl.svasquezm.proto.Models.Pet.getDefaultInstance());
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public cl.svasquezm.proto.Models.Pet.Builder addPetsBuilder(
          int index) {
        return getPetsFieldBuilder().addBuilder(
            index, cl.svasquezm.proto.Models.Pet.getDefaultInstance());
      }
      /**
       * <code>repeated .cl.svasquezm.proto.Pet pets = 4;</code>
       */
      public java.util.List<cl.svasquezm.proto.Models.Pet.Builder> 
           getPetsBuilderList() {
        return getPetsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cl.svasquezm.proto.Models.Pet, cl.svasquezm.proto.Models.Pet.Builder, cl.svasquezm.proto.Models.PetOrBuilder> 
          getPetsFieldBuilder() {
        if (petsBuilder_ == null) {
          petsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cl.svasquezm.proto.Models.Pet, cl.svasquezm.proto.Models.Pet.Builder, cl.svasquezm.proto.Models.PetOrBuilder>(
                  pets_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          pets_ = null;
        }
        return petsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cl.svasquezm.proto.User)
    }

    // @@protoc_insertion_point(class_scope:cl.svasquezm.proto.User)
    private static final cl.svasquezm.proto.Models.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cl.svasquezm.proto.Models.User();
    }

    public static cl.svasquezm.proto.Models.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cl.svasquezm.proto.Models.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cl_svasquezm_proto_Pet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cl_svasquezm_proto_Pet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cl_svasquezm_proto_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cl_svasquezm_proto_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/models.proto\022\022cl.svasquezm.proto" +
      "\"!\n\003Pet\022\014\n\004type\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"\237\001\n\004" +
      "User\022\014\n\004name\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\022+\n\004typ" +
      "e\030\003 \001(\0162\035.cl.svasquezm.proto.User.Type\022%" +
      "\n\004pets\030\004 \003(\0132\027.cl.svasquezm.proto.Pet\"&\n" +
      "\004Type\022\007\n\003WEB\020\000\022\n\n\006MOBILE\020\001\022\t\n\005ADMIN\020\002b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cl_svasquezm_proto_Pet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cl_svasquezm_proto_Pet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cl_svasquezm_proto_Pet_descriptor,
        new java.lang.String[] { "Type", "Name", });
    internal_static_cl_svasquezm_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cl_svasquezm_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cl_svasquezm_proto_User_descriptor,
        new java.lang.String[] { "Name", "Email", "Type", "Pets", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
